function just_letter_indexing(s)
% function scalebar(x1,y1)
% draws scalebar on image

%h = text( x1, y1 ,texlabel(s));
%set(h,'Color',[1 1 1],'HorizontalAlignment','center','FontSize',20);

annotation(gcf,'textbox','String',{s},'FontSize',36,...
    'FontName','Arial',...
    'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.2734 0.8247 0.07031 0.06232],...
    'Color',[1 1 1]);